# Site settings
title: "t-o.ie"
description: "These are the ramblings of a dad, web developer & cyber security enthusiast."
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "to-ie"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
